name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 217.196.60.38
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/autofaros
          git pull
          pm2 restart all
